// Parity tests: the new physics kernels must reproduce the LEGACY solver's
// outputs bit-for-bit on a fixed synthetic setup (RampGrid6020 geometry +
// deterministic fields). Reference values were generated by linking a probe
// against the legacy objects; see tests/goldens_physics.inc.

#include <gtest/gtest.h>

#include <cmath>

#include "physics/dependent_variables.hpp"
#include "physics/gradients.hpp"
#include "physics/viscous_flux.hpp"

namespace {

using namespace ns;
using namespace ns::physics;

#include "goldens_physics.inc"

constexpr int kNx = 60, kNy = 20, kNg = 2;
constexpr const char* kGridPath = NS_SOURCE_DIR "/input/RampGrid6020.dat";

struct ParityRig {
    StructuredMesh mesh{kNx, kNy, kNg};
    MeshMetrics metrics{compute_metrics(mesh)};
    MultiField<double> dv{8, kNx, kNy, kNg};

    ParityRig() {
        // Must match the golden-generation probe field exactly.
        for (int i = -kNg; i < kNx + kNg; ++i) {
            for (int j = -kNg; j < kNy + kNg; ++j) {
                const double a = 0.3 * (i + 2), b = 0.47 * (j + 2);
                const double w1 = std::sin(a) * std::cos(b);
                const double w2 = std::cos(0.21 * a) * std::sin(0.53 * b);
                dv(0, i, j) = 1.0 + 0.2 * w1;
                dv(1, i, j) = 120.0 * (0.5 + 0.3 * w2);
                dv(2, i, j) = -35.0 + 12.0 * w1;
                dv(4, i, j) = 260.0 + 80.0 * w1;
                dv(3, i, j) = 101325.0 * (0.8 + 0.05 * w2);
                dv(5, i, j) = 310.0 + 15.0 * w2;
                dv(6, i, j) = 1.8e-5 * (1.0 + 0.4 * w2);
                dv(7, i, j) = 0.9 * (1.0 + 0.3 * w1);
            }
        }
    }
};

TEST(PhysicsParity, GreenGaussFaceGradientsMatchLegacyBitwise) {
    // The rig builds its own grid; re-load from file so node coordinates come
    // from the same source as the probe run.
    auto loaded = StructuredMesh::load_legacy(kGridPath, kNx, kNy, kNg);
    ASSERT_TRUE(loaded.has_value()) << loaded.error().message;
    ParityRig rig;  // deterministic dv fill
    rig.mesh = std::move(*loaded);
    rig.metrics = compute_metrics(rig.mesh);

    MultiField<double> gradfi(6, kNx + 1, kNy + 1, kNg);
    MultiField<double> gradfj(6, kNx + 1, kNy + 1, kNg);
    gradfi.fill(0.0);
    gradfj.fill(0.0);
    green_gauss_face_gradients(rig.mesh, rig.metrics, rig.dv, gradfi, gradfj);

    for (const auto& g : goldens::gradfi_samples)
        for (int k = 0; k < 6; ++k)
            EXPECT_DOUBLE_EQ(gradfi(k, g.i, g.j), g.v[k])
                << "gradfi plane " << k << " at (" << g.i << "," << g.j << ")";

    for (const auto& g : goldens::gradfj_samples)
        for (int k = 0; k < 6; ++k)
            EXPECT_DOUBLE_EQ(gradfj(k, g.i, g.j), g.v[k])
                << "gradfj plane " << k << " at (" << g.i << "," << g.j << ")";
}

TEST(PhysicsParity, ViscousFluxMatchesLegacyBitwise) {
    auto loaded = StructuredMesh::load_legacy(kGridPath, kNx, kNy, kNg);
    ASSERT_TRUE(loaded.has_value()) << loaded.error().message;
    ParityRig rig;
    rig.mesh = std::move(*loaded);
    rig.metrics = compute_metrics(rig.mesh);

    MultiField<double> gradfi(6, kNx + 1, kNy + 1, kNg);
    MultiField<double> gradfj(6, kNx + 1, kNy + 1, kNg);
    gradfi.fill(0.0);
    gradfj.fill(0.0);
    green_gauss_face_gradients(rig.mesh, rig.metrics, rig.dv, gradfi, gradfj);

    MultiField<double> diss(4, kNx, kNy, kNg);
    diss.fill(0.0);
    accumulate_viscous_flux(rig.mesh, rig.metrics, rig.dv, gradfi, gradfj, diss);

    for (const auto& g : goldens::diss_samples)
        for (int k = 0; k < 3; ++k)
            EXPECT_DOUBLE_EQ(diss(k + 1, g.i, g.j), g.v[k])
                << "diss plane " << k + 1 << " at (" << g.i << "," << g.j << ")";
}

TEST(PhysicsParity, DependentVariablesMatchLegacyBothFormulations) {
    IdealGas eos{};  // gamma=1.4, R=286.92, Pr=0.72 -- legacy constants

    struct Case {
        double rho, u, v, p;
    };
    const Case cases[] = {
        {1.2, 480.0, -30.0, 95.5e3},
        {0.45, 1150.0, 210.0, 1240.0},
        {3.7, 12.0, -4.0, 210000.0},
    };

    MultiField<double> cv(4, 4, 4, 1);
    MultiField<double> dv(8, 4, 4, 1);

    // Nondimensional formulation
    {
        TransportScaling s{};
        s.re_inf = 5000.0;
        s.mach_inf = 2.0;
        for (std::size_t c = 0; c < std::size(cases); ++c) {
            cv(0, 2, 2) = cases[c].rho;
            cv(1, 2, 2) = cases[c].rho * cases[c].u;
            cv(2, 2, 2) = cases[c].rho * cases[c].v;
            cv(3, 2, 2) = cases[c].p / eos.gamma_minus_1() +
                          0.5 * cases[c].rho * (cases[c].u * cases[c].u +
                                                cases[c].v * cases[c].v);
            compute_dependent_variables_at(cv, dv, 2, 2, eos, Formulation::Nondimensional,
                                           s);
            for (int k = 0; k < 8; ++k)
                EXPECT_DOUBLE_EQ(dv(k, 2, 2), goldens::depvars_nd[c].v[k])
                    << "DV_ND case " << c << " plane " << k;
        }
    }

    // Dimensional formulation
    {
        TransportScaling s{};
        s.ref_visc = 1.789e-5;
        s.cp = 1005.0;
        for (std::size_t c = 0; c < std::size(cases); ++c) {
            cv(0, 2, 2) = cases[c].rho;
            cv(1, 2, 2) = cases[c].rho * cases[c].u;
            cv(2, 2, 2) = cases[c].rho * cases[c].v;
            cv(3, 2, 2) = cases[c].p / eos.gamma_minus_1() +
                          0.5 * cases[c].rho * (cases[c].u * cases[c].u +
                                                cases[c].v * cases[c].v);
            compute_dependent_variables_at(cv, dv, 2, 2, eos, Formulation::Dimensional, s);
            for (int k = 0; k < 8; ++k)
                EXPECT_DOUBLE_EQ(dv(k, 2, 2), goldens::depvars_dim[c].v[k])
                    << "DV_DIM case " << c << " plane " << k;
        }
    }
}

// ---------------------------------------------------------------------------
// Property tests (independent of goldens)
// ---------------------------------------------------------------------------
TEST(EosProperties, PrimConsRoundTripIsIdentity) {
    IdealGas eos{};
    const PrimitiveState w{0.83, 512.5, -77.25, 44100.0};
    const ConservedState c = eos.conserved(w);
    const PrimitiveState back = eos.primitive(c);
    EXPECT_DOUBLE_EQ(back.rho, w.rho);
    EXPECT_DOUBLE_EQ(back.u, w.u);
    EXPECT_DOUBLE_EQ(back.v, w.v);
    EXPECT_DOUBLE_EQ(back.p, w.p);
}

TEST(EosProperties, AnalyticRelationsHold) {
    IdealGas eos{};
    const double rho = 1.225, p = 101325.0;
    EXPECT_NEAR(eos.sound_speed(rho, p), std::sqrt(1.4 * p / rho), 1e-9);
    EXPECT_DOUBLE_EQ(eos.temperature(rho, p), p / (rho * eos.gas_constant));
    const ConservedState c = eos.conserved({rho, 0.0, 0.0, p});
    EXPECT_DOUBLE_EQ(c.e, p / eos.gamma_minus_1());
    EXPECT_DOUBLE_EQ(eos.pressure(c.rho, c.rhou, c.rhov, c.e), p);
}

TEST(TransportProperties, DimensionalFormEqualsClassicSutherland) {
    // With ref_visc = mu(T0) of the classic law mu = C2*T^1.5/(T+S), the
    // ported dimensional form must reduce to exactly that law.
    constexpr double C2 = 1.458e-6;
    TransportScaling s{};
    s.ref_visc = C2 * std::pow(kSutherlandT0, 1.5) / (kSutherlandT0 + kSutherlandS);
    for (double t : {200.0, 288.15, 450.0, 1100.0}) {
        const double classic = C2 * std::pow(t, 1.5) / (t + kSutherlandS);
        EXPECT_NEAR(sutherland_viscosity_dim(t, s), classic, 1e-12 * classic);
    }
}

}  // namespace
